#Run this command on your server "ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts".
name: Push To Test WorkFlow

on:
  push:
    branches: 
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install --force
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
  deploy:
    runs-on: ubuntu-latest
    # needs: build
    steps:
      - name: Deploy to test server
        uses: appleboy/ssh-action@master
        env:
            PAT: ${{ secrets.PAT }}
            DEPLOY_PATH_TEST: ${{ secrets.DEPLOY_PATH_TEST}}
            TEST_USER: ${{ secrets.TEST_USER }}
            TEST_OWNER: ${{ secrets.TEST_OWNER }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: PAT, DEPLOY_PATH_TEST, TEST_USER, TEST_OWNER
          script: |
            su - $TEST_USER
            sudo mkdir -p /tmp/test
            cd /tmp/test && sudo git clone https://$PAT@github.com/whocoded/Haba-Customer-Care.git
            sudo chmod -R 777 /tmp/test/Haba-Customer-Care
            cd /tmp/test/Haba-Customer-Care
            sudo git checkout -f test
            sudo npm install --force && npm run build
            sudo rm -r $DEPLOY_PATH_TEST/public_html-old
            sudo mv $DEPLOY_PATH_TEST/public_html $DEPLOY_PATH_TEST/public_html-old
            sudo mkdir -p $DEPLOY_PATH_TEST/public_html
            sudo mv /tmp/test/Haba-Customer-Care/dist/* $DEPLOY_PATH_TEST/public_html
            sudo cp /tmp/robots/robots.txt $DEPLOY_PATH_TEST/public_html
            sudo rm -r /tmp/test/Haba-Customer-Care
            sudo chown -R $TEST_OWNER:$TEST_OWNER $DEPLOY_PATH_TEST/public_html
            sudo chmod -R 0755 $DEPLOY_PATH_TEST/public_html